version: "3.8"
services:
    backend-api:
        build:
            dockerfile: Dockerfile
            context: ./backend-api
        depends_on:
            - postgres
        env_file:
            - ./.env
        ports:
            - "8080:3000"
        volumes:
            - backend:/var/src/app
    frontend-react:
        build:
            dockerfile: Dockerfile
            context: ./frontend-react/
        depends_on:
            - backend-api
        env_file:
            - ./.env
        ports:
            - "8081:3000"
        volumes:
            - frontend:/var/src/app/src
    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        env_file:
            - ./.env
        volumes:
            - database:/var/lib/postgresql/data
    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - "8082:80"
        env_file:
            - ./.env
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

volumes:
    database:
    pgadmin:
    backend:
    frontend:

# should include netwoks properly to separate service's
# should separate front-end from back-end then i can adapt networks 